function [errForward,...
          errBackward, ...
          errFEM, ...
          errFrac] = find_error(nodalCoords,...
                                pressureAnalytical,... 
                                pressureForward,...
                                pressureBackward, ...
                                pressureFEM, ... 
                                pressureFrac)

errForward = abs((pressureForward - pressureAnalytical) ./ pressureAnalytical);
errBackward = abs((pressureBackward - pressureAnalytical) ./ pressureAnalytical);
errFEM = abs((pressureFEM - pressureAnalytical) ./ pressureAnalytical);
errFrac = abs((pressureFrac - pressureAnalytical) ./ pressureAnalytical);

end